<?php

/**
 * Invoke hook_permission().
 */
function flashcard_permission() {
  return array(
    'flashcard learn' => array(
      'title' => t('Learn using flashcards'),
      'description' => t('Allow users to use flashcards to learn'),
    ),
    'flashcard import' => array(
      'title' => t('Use import'),
      'description' => t('Allow user to import flashcards from files'),
    ),
  );
}

/**
 * Invoke hook_menu().
 */
function flashcard_menu() {

  $items['flashcard'] = array(
    'title' => t('Flashcards'),
    'page callback' => 'flashcard_list',
    'access arguments' => array('flashcard list'),
    'menu_name' => 'main-menu',
    'weight' => 100,
  );

  $items['flashcard/import'] = array(
    'title' => t('Import flashcards'),
    'page callback' => 'flashcard_show_imports',
    'access arguments' => array('flashcard import'),
    'menu_name' => 'main-menu',
    'weight' => 130,
  );

  $items['flashcard/import/%'] = array(
    'title' => t('Process import file'),
    'page callback' => 'flashcard_process_import',
    'page arguments' => array(2),
    'access arguments' => array('flashcard import'),
  );

  $items['flashcard/train'] = array(
    'page callback' => 'flashcard_train',
    'access arguments' => array('flashcard learn'),
    'menu_name' => 'main-menu',
    'weight' => 200,
  );

  $items['flashcard/config'] = array(
    'title' => t('Settings'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('flashcard_config_form'),
    'access arguments' => array('flashcard learn'),
    'menu_name' => 'main-menu',
  );

  $items['flashcard/mp3script'] = array(
    'title' => 'Mp3 Script',
    'description' => 'Script builder for linux command line to generate mp3 files for audio listenning',
    'access arguments' => array('flashcard learn'),
    'page callback' => 'flashcard_mp3_script',
    'menu_name' => 'main-menu',
    'weight' => 250,
  );

  $items['flashcard/stats'] = array(
    'title' => 'Statistics',
    'desription' => 'A graph showing the learing progress.',
    'page callback' => 'flashcard_progress_chart',
    'access arguments' => array('flashcard learn'),
    'menu_name' => 'main-menu',
  );

  $items['flashcard/toggle/hide/nojs/%'] = array(
    'description' => 'Toggles hidde/show state of the flashcard',
    'page callback' => 'flashcard_toggle_hide',
    'page arguments' => array(3, 4),
    'access arguments' => array('flashcard learn'),
    'type' => MENU_CALLBACK,
  );

  $items['flashcard/toggle/hide/ajax/%'] = array(
    'delivery callback' => 'ajax_deliver',
  ) + $items['flashcard/toggle/hide/nojs/%'];

  $items['flashcard/toggle/audioreview/nojs/%'] = array(
    'description' => 'Toggles audio review state of the flashcard',
    'page callback' => 'flashcard_toggle_audioreview',
    'page arguments' => array(3, 4),
    'access arguments' => array('flashcard learn'),
    'type' => MENU_CALLBACK,
  );

  $items['flashcard/toggle/audioreview/ajax/%'] = array(
    'delivery callback' => 'ajax_deliver',
  ) + $items['flashcard/toggle/audioreview/nojs/%'];

  $items['flashcard/toggle/writereview/nojs/%'] = array(
    'description' => 'Toggles write review state of the flashcard',
    'page callback' => 'flashcard_toggle_writereview',
    'page arguments' => array(3, 4),
    'access arguments' => array('flashcard learn'),
    'type' => MENU_CALLBACK,
  );

  $items['flashcard/toggle/writereview/ajax/%'] = array(
    'delivery callback' => 'ajax_deliver',
  ) + $items['flashcard/toggle/writereview/nojs/%'];

  $items['flashcard/delete/recording/nojs/%'] = array(
    'description' => 'Deletes the user specific recording file.',
    'page callback' => 'flashcard_delete_recording',
    'page arguments' => array(3, 4),
    'access arguments' => array('flashcard learn'),
    'type' => MENU_CALLBACK,
  );

  $items['flashcard/delete/recording/ajax/%'] = array(
    'delivery callback' => 'ajax_deliver',
  ) + $items['flashcard/delete/recording/nojs/%'];

  $items['flashcard/audioupload'] = array(
    'description' => 'Handles recorder on page and uploaded files.',
    'page callback' => 'flashcard_upload_audio',
    'access arguments' => array('flashcard learn'),
  );

  return $items;
}

/**
 * Function flashcard_create().
 */
function flashcard_create() {
  return (object) array(
    'original' => '',
    'transcript' => '',
    'translation' => '',
    'sound' => '',
  );
}

/**
 * Invoke hook_theme().
 */
function flashcard_theme($existing, $type, $theme, $path) {
  return [
    'flashcard_display' => [
      'variables' => [
        'card' => NULL,
        'nextCard' => NULL,
        'settings' => NULL,
      ],
      'render element' => 'element',
      'template' => 'flashcard-display',
    ],
    'flashcard_list' => [
      'variables' => [
        'rows' => array(),
        'recdir' => '',
      ],
      'render element' => 'element',
      'template' => 'flashcard-list',
    ],
    'flashcard_progress' => [
      'variables' => [
        'stats' => (object) array(
          'total_cards' => 0,
          'hiden_cards' => 0,
          'ongoing_cards' => 0,
          'to_audioreview' => 0,
          'to_writereview' => 0,
        ),
      ],
      'render element' => 'element',
      'template' => 'flashcard-progress',
    ],
  ];
}

/**
 * Function flashcard_load_stats().
 */
function flashcard_load_stats($cid) {
  global $user;
  $stats = (object) array(
    'cid' => $cid,
    'uid' => $user->uid,
    'views_count' => 0,
    'hide' => 0,
    'data' => serialize(array()),
  );
  $query = db_select('flashcard_user_data', 't')
    ->fields('t')
    ->condition('t.uid', $user->uid)
    ->condition('t.cid', $cid);
  $result = $query->execute();
  $result = $result->fetchObject();
  if ($result) {
    $stats = $result;
  }
  $stats->data = unserialize($stats->data);
  return $stats;
}

/**
 * Function flashcard_save_stats().
 */
function flashcard_save_stats($stats) {
  global $user;
  $rez = db_select('flashcard_user_data', 't')
    ->fields('t', array('cid'))
    ->condition('cid', $stats->cid)
    ->condition('uid', $user->uid)
    ->execute()->fetchObject();
  if (!drupal_write_record('flashcard_user_data', $stats, $rez ? ['cid', 'uid'] : array())) {
    drupal_set_message(t('Failed to save statistics for flashcard @cid', array('@cid' => $stats->cid)));
  }
}

/**
 * Function flashcard_hide().
 */
function flashcard_hide($cid) {
  $stats = flashcard_load_stats($cid);
  if ($stats) {
    $stats->hide = 1;
    flashcard_save_stats($stats);
  }
}

/**
 * Function flashcard_audio_review().
 */
function flashcard_audio_review($cid) {
  $stats = flashcard_load_stats($cid);
  if ($stats) {
    $stats->audioreview = 1;
    flashcard_save_stats($stats);
  }
}

/**
 * Function flashcard_audio_review().
 */
function flashcard_write_review($cid) {
  $stats = flashcard_load_stats($cid);
  if ($stats) {
    $stats->writereview = 1;
    flashcard_save_stats($stats);
  }
}

/**
 * Function flashcard_user_recording_dir().
 */
function flashcard_user_recording_dir() {
  global $user;
  $recdir = 'public://flashcard/recordings/' . $user->uid; 
  $recdir = drupal_realpath($recdir);
  return $recdir;
}

/**
 * Function flashcard_recording_file().
 */
function flashcard_recording_file($cid) {
  $fname = flashcard_user_recording_dir() . '/' . $cid . '.mp3';
  return file_exists($fname) ? $fname : 0;
}

/**
 * Function flashcard_recording_url().
 */
function flashcard_recording_url($cid) {
  global $user;
  if (flashcard_recording_file($cid)) {
    return file_create_url('public://flashcard/recordings/' . $user->uid . '/' . $cid . '.mp3');
  }
  return 0;
}

/**
 * Function flashcard_train().
 */
function flashcard_train($cid = 0, $cmd = FALSE, $arg = FALSE) {
  $build = array();

  if (!$cid) {
    $card = flashcard_load_next_card(0);
    if (!$card) {
      return array('#markup' => t('No flashcards left for learning for given criteria'));
    }
    $cid = $card->cid;
  }

  global $user;
  drupal_set_breadcrumb(array());

  $set = flashcard_get_user_settings('training');

  $stats = flashcard_load_stats($cid);
  if ($stats) {
    $stats->views_count++;
    flashcard_save_stats($stats);
  }

  if ($cmd == 'h') {
    flashcard_hide($arg);
  }
  elseif ($cmd == 'a') {
    drupal_set_message(t('Card @cid added to audio review group.', array('@cid' => $arg)));
    flashcard_audio_review($arg);
  }
  elseif ($cmd == 'w') {
    drupal_set_message(t('Card @cid added to write review group.', array('@cid' => $arg)));
    flashcard_write_review($arg);
  }
  elseif ($cmd == 'aw') {
    drupal_set_message(t('Card @cid added to audio and write review groups.', array('@cid' => $arg)));
    flashcard_audio_review($arg);
    flashcard_write_review($arg);
  }

  $modpath = drupal_get_path('module', 'flashcard');
  $soundpath = $modpath . '/audio';

  $recDir = 'public://flashcard/recordings/' . $user->uid; 
  file_prepare_directory($recDir, FILE_CREATE_DIRECTORY);
  $recPath = file_create_url($recDir);

  drupal_add_js($modpath . '/js/flashcard.js');
  drupal_add_css($modpath . '/css/flashcard.css');
  drupal_add_js($modpath . '/js/flashcardrec.js');
  drupal_add_css($modpath . '/css/flashcardrec.css');

  $default = array(
    'current' => 1,
  );
  $settings = variable_get('flashcard_' . $user->uid, $default);
  $settings += $default;

  $query = db_select('flashcard', 't');
  $query->fields('t');
  $query->leftJoin('flashcard_user_data', 'd', 't.cid = d.cid');
  $query->fields('d');
  $query->condition(db_or()->condition('d.uid', $user->uid)->condition('d.cid', NULL));
  $query->condition('t.cid', $cid);
  $result = $query->execute();
  $card = $result->fetchObject();

  $toReplace = array("/^\[(sound\:)/", "/\]$/");
  $card->sound = $soundpath . '/' . preg_replace($toReplace, '', trim($card->sound));
  
  $card->stats = $stats;

  drupal_add_library('system', 'drupal.ajax');
  $card->hide_link = flashcard_get_toggle_hide_link($card->cid, $card->hide);
  $card->audioreview_link = flashcard_get_toggle_audioreview_link($card->cid, $card->audioreview);
  $card->writereview_link = flashcard_get_toggle_writereview_link($card->cid, $card->writereview);

  $recFile = flashcard_user_recording_dir() . '/' . $card->cid . '.mp3';
  $card->recording = file_exists($recFile) ? $card->cid : 0;
  $card->delete_recording_link = flashcard_get_delete_recording_link($card->cid, $card->recording);

  $card->recdir = $recPath;
  $rows = array();

  $card->recording = flashcard_recording_url($cid);

  $build['flashcard'] = array(
    '#theme' => 'flashcard_display',
    '#card' => $card,
    '#nextCard' => flashcard_load_next_card($cid),
    '#settings' => (object) $set,
    'nothing' => NULL,
  );

  $build['links'] = array(
    '#theme' => 'item_list',
    '#items' => flashcard_get_links('train'),
  );
  return $build;
}

/**
 * Function flashcard_list().
 */
function flashcard_list() {

  global $user;

  drupal_add_library('system', 'drupal.ajax');

  $recDir = 'public://flashcard/recordings/' . $user->uid; 
  file_prepare_directory($recDir, FILE_CREATE_DIRECTORY);
  $recPath = file_create_url($recDir);
  $recDir = drupal_realpath($recDir);

  $build = array();
  
  $query = db_select('flashcard', 't')
    ->extend('PagerDefault');
  
  $query->leftJoin('flashcard_user_data', 'd', 't.cid=d.cid');
  //$and = db_and()->condition('d.uid', $user->uid);
  //$and->condition('d.hide', 0);
  //$or = db_or()->condition('d.cid', NULL)->condition($and);
  //$query->condition($or);
  $query->fields('t', array());
  $query->fields('d', array('views_count', 'hide', 'audioreview', 'writereview'));
  
  $result = $query
      ->limit(30)
      ->orderBy('t.cid')
      ->execute();
  
  $rows = array();
  foreach ($result as $row) {
    $row->hide_link = flashcard_get_toggle_hide_link($row->cid, $row->hide);
    $row->audioreview_link = flashcard_get_toggle_audioreview_link($row->cid, $row->audioreview);
    $row->writereview_link = flashcard_get_toggle_writereview_link($row->cid, $row->writereview);

    $recFile = $recDir . '/' . $row->cid . '.mp3';
    $row->recording = file_exists($recFile) ? $row->cid : 0;
    $row->delete_recording_link = flashcard_get_delete_recording_link($row->cid, $row->recording);
    $rows[$row->cid] = $row;
  }

  $modpath = drupal_get_path('module', 'flashcard');
  
  drupal_add_js($modpath . '/js/flashcard.list.js');
  drupal_add_js($modpath . '/js/flashcardrec.js');
  drupal_add_css($modpath . '/css/flashcard-list.css');
  drupal_add_css($modpath . '/css/flashcardrec.css');

  $build['flashcards_list'] = array(
    '#theme' => 'flashcard_list',
    '#rows' => $rows,
    '#empty' => t('There are no records found in the db'),
    '#recdir' => $recPath,
  );
  
  $build['pager_pager'] = array(
    '#theme' => 'pager',
  );

  $build['links'] = array(
    '#theme' => 'item_list',
    '#items' => flashcard_get_links('list'),
  );

  return $build;
}

/**
 * Function flashcard_get_links().
 */
function flashcard_get_links($exclude = FALSE) {
  $links = array(
    'list' => l(t('Train'), 'flashcard'),
    'train' => l(t('Train'), 'flashcard/train'),
    'config' => l(t('Config'), 'flashcard/config'),
    'stats' => l(t('Statistics'), 'flashcard/stats'),
    'mp3' => l(t('Build Mp3'), 'flashcard/mp3script', array(
      '#attributes' => array(
        'target' => '_blank',
      ),
    )),
  );
  if ($exclude) {
    if (isset($links[$exclude])) unset($links[$exclude]);
  }
  return $links;
}

/**
 * Function _flashcard_load_next_card().
 */
function _flashcard_load_next_card($cid) {
  global $user;
  $set = flashcard_get_user_settings('training');
  $query = db_select('flashcard', 't');
  $query->fields('t', array('cid'));
  $query->leftJoin('flashcard_user_data', 'd', 't.cid=d.cid');
  // cards that are not hidden:
  $and = db_and()->condition(db_or()->condition('d.uid', $user->uid)->condition('d.cid', NULL));

  if ($set->play_hidden_cards) {
    $and->condition('d.hide', 1);
  }
  elseif(!$set->play_unseen_cards) {
    $and->condition('d.hide', 0);
  }
  // additional conditions
  $or = db_or();
  if ($set->play_unseen_cards) {
    $or->condition('d.cid', NULL);
  }
  if ($set->play_audioreview) {
    $or->condition('d.audioreview', 1);
  }
  if ($set->play_writereview) {
    $or->condition('d.audioreview', 1);
  }
  if ($or->count()) {
    $and->condition($or);
  }

  // include cards that user never touch before:
  //$or = db_or()->condition('d.cid', NULL)->condition($and);
  $query->condition($and);
  $query->condition('t.cid', $cid, '>');
  $query->condition('t.cid', $set->startat, '>=');
  $query->range(0,1);
  $query->orderBy('t.cid');
  $rez = $query->execute();
  return $rez->fetchObject();
}

/**
 * Function flashcard_load_next_card().
 */
function flashcard_load_next_card($cid) {
  $card = _flashcard_load_next_card($cid);
  if (!$card) return _flashcard_load_next_card(0);
  return $card;
}

/**
 * Function flashcard_mp3_script().
 */
function flashcard_mp3_script() {

  global $user;

  $outdir = 'public://flashcard/mp3out'; 
  file_prepare_directory($outdir, FILE_CREATE_DIRECTORY);
  $outdir = drupal_realpath($outdir);

  $recdir = flashcard_user_recording_dir();

  $query = db_select('flashcard_user_data', 'd');
  $query->leftJoin('flashcard', 'c', 'd.cid=c.cid');
  $query->fields('c', array('cid', 'sound'));
  $query->condition('d.uid', $user->uid);
  $query->condition('d.audioreview', 1);
  $query->orderBy('d.cid');
  $rez = $query->execute();

  $modpath = drupal_get_path('module', 'flashcard');
  $soundpath = $modpath . '/audio';

  $toReplace = array("/^\[(sound\:)/", "/\]$/");
  $rzArray = array();
  $count = 0;
  while($card = $rez->fetchObject()) {
    $card->sound = preg_replace($toReplace, '', trim($card->sound));

    $rzArray[$count][] = $card->sound;
    $recordFile = $recdir . '/' . $card->cid . '.mp3';
    if (file_exists($recordFile)) {
      $rzArray[$count][] = $recordFile;
      $rzArray[$count][] = $card->sound;
    }
    $rzArray[$count][] = $card->sound;

    if (count($rzArray[$count]) >= 50){
      $count++;
    }
  }

  $batch = array(
    'operations' => array(),
    'finished' => 'flashcard_mp3_create_finished',
    'title' => t('Create mp3 file for listenning.'),
    'init_message' => t('Mp3 creation is starting'),
    'process_message' => t('Processed @current out of @total.'),
    'error_message' => t('Import has encountered an error.'),
  );

  $progress = 0;
  $limit = 1;

  $options ="-vn -ar 44100 -ac 2 -ab 192k -f mp3";
  $options ="-vn -ar 22050 -ac 2 -ab 45k -f mp3";
  $max = count($rzArray)-1;
  array_map('unlink', glob($outdir ."/*.mp3"));
  while ($progress <=$max) {
    $outputFname = $outdir . '/' . sprintf("%'.04d", $progress) . '.mp3';
    $command = 'cd "' . $soundpath . '" && ffmpeg -i "concat:' . implode("|", $rzArray[$progress]) . '" -acodec copy ' . $options . ' ' . $outputFname;
    $batch['operations'][] = array('flashcard_mp3_create', array($command, $progress, $limit));
    $progress = $progress + $limit;
  }

  batch_set($batch);
  batch_process('flashcard');
}

/**
 * Function flashcard_mp3_create().
 *
 * Executes the bash command to combine the mp3 parts into one single audio file
 * for listenning.
 */
function flashcard_mp3_create($command, $progress, $limit, &$context) {
  `$command`;
  $progress = $progress+$limit;
  $context['message'] = 'Now processings ' . $progress . ' - ' . $context['results'][0] . ' imported';
}

/**
 * Function flashcard_mp3_creation_finished().
 */
function flashcard_mp3_creation_finished($success, $results, $operations) {
  if ($success) {
    drupal_set_message('Mp3 Creation is complete. Check private://flashcard/mp3out directory');
  }
  else {
    $error_operation = reset($operations);
    $message = t('An error occured while processing %error_operation %error_operation with arguments: @arguments', array(
            '%error_operation' => $error_operation[0],
            '@arguments' => print_r($error_operation[1], TRUE)
    ));
    drupal_set_message($message, 'error');
  }
  
}

/**
 * Function flashcard_show_imports().
 */
function flashcard_show_imports() {
  $build['info'] = array(
    '#markup' => 'Flashcards inport',
  );

  $path = drupal_get_path('module', 'flashcard') . '/data';
  $files = glob($path . "/*.txt");

  foreach($files as $i=>$f) {
    $f = basename($f, '.txt');
    $build['line_' . $i] = array(
      "#markup" => '<p>' . l($f, 'flashcard/import/' . $f) . '</p>',
    );
  }

  return $build;
}

/**
 * Function flashcard_process_import().
 */
function flashcard_process_import($fname) {
  $build = array();

  $fname = drupal_get_path('module', 'flashcard') . '/data/' . $fname . '.txt';
  $fname = drupal_realpath($fname);
  $lines = file($fname);
  if (!$lines) {
    $build = array('#markup' => 'Nothing to import from file ' . $fname);
    return $Build;
  }

  $batch = array(
    'operations' => array(),
    'finished' => 'flashcard_process_import_finished',
    'title' => t('Import from file @fname', array('@fname' => basename($fname, '.txt'))),
    'init_message' => t('Import is starting'),
    'process_message' => t('Processed @current out of @total.'),
    'error_message' => t('Import has encountered an error.'),
  );

  $progress = 0;
  $limit = 50;
  $max = count($lines);
  while ($progress <=$max) {
    $batch['operations'][] = array('flashcard_import_cards', array($fname, $progress, $limit));
    $progress = $progress + $limit;
  }

  batch_set($batch);
  batch_process('flashcard/import');
  //return $build;
}

/**
 * Function flashcard_import_cards().
 */
function flashcard_import_cards($fname, $progress, $limit, &$context) {
  
  $lines = file($fname);
  for($i = $progress; $i<=$progress+$limit; $i++){
    $parts = explode("\t", trim($lines[$i]));
    list($translation, $transcript, $original, $sound) = $parts;
    $soud = preg_replace(array("/^\[/", "/\]$/"), '', $sound);
    $query = db_select('flashcard', 't')
      ->fields('t', array('cid'));
    $query->condition('t.original', $original);
    $result = $query->execute();
    if (!$result->fetchAssoc()) {
      $query = db_insert('flashcard')
        ->fields(array(
          'original' => $original,  
          'transcript' => $transcript,
          'translation' => $translation,
          'sound' => $sound,
        ));
      $query->execute();
    }
  }
  $progress = $progress+$limit;
  $context['message'] = 'Now processings ' . $progress . ' - ' . $context['results'][0] . ' imported';
}

/**
 * Function flashcard_process_import_finished().
 */
function flashcard_process_import_finished($success, $results, $operations) {
  if ($success) {
    drupal_set_message('Import is complete');
  }
  else {
    $error_operation = reset($operations);
    $message = t('An error occured while processing %error_operation %error_operation with arguments: @arguments', array(
            '%error_operation' => $error_operation[0],
            '@arguments' => print_r($error_operation[1], TRUE)
    ));
    drupal_set_message($message, 'error');
  }
}

/**
 * Function flashcard_get_toggle_hide_link().
 */
function flashcard_get_toggle_hide_link($cid, $hide) {
  $query = array(
    'thok' => drupal_get_token('flashcard_toggle_hide' . $cid),
  ) + drupal_get_destination();
  return l('&#128065;', 'flashcard/toggle/hide/nojs/' . $cid, array(
    'query' => $query, 
    'html' => TRUE,
    'attributes' => array(
      'id' => 'flashcard-toogle-hide-link-' . $cid,
      'class' => array('use-ajax flashcard-hide-button', $hide ? 'flashcard-hidden' : 'flashcard-shown'),
    )
  ));
}

/**
 * Function flashcard_get_toggle_audioreview_link().
 */
function flashcard_get_toggle_audioreview_link($cid, $value) {
  $query = array(
    'taok' => drupal_get_token('flashcard_toggle_audioreview' . $cid),
  ) + drupal_get_destination();

  $classes = ['use-ajax', 'flashcard-audioreview-button'];
  if ($value) {
    $classes[] = 'flashcard-audioreview-enabled';
  }
  return l('&#128266;', 'flashcard/toggle/audioreview/nojs/' . $cid, array(
    'query' => $query, 
    'html' => TRUE,
    'attributes' => array(
      'id' => 'flashcard-toogle-audio-link-' . $cid,
      'class' => $classes,
    )
  ));
  
}

/**
 * Function flashcard_get_toggle_writereview_link().
 */
function flashcard_get_toggle_writereview_link($cid, $value) {
  $query = array(
    'twok' => drupal_get_token('flashcard_toggle_writereview' . $cid),
  ) + drupal_get_destination();

  $classes = ['use-ajax', 'flashcard-writereview-button'];
  if ($value) {
    $classes[] = 'flashcard-writereview-enabled';
  }
  return l('&#x270E;', 'flashcard/toggle/writereview/nojs/' . $cid, array(
    'query' => $query, 
    'html' => TRUE,
    'attributes' => array(
      'id' => 'flashcard-toogle-write-link-' . $cid,
      'class' => $classes,
    )
  ));
  
}

/**
 * Function flashcard_toggle_hide().
 */
function flashcard_toggle_hide($ajax, $cid) {

  $is_ajax = $ajax === 'ajax';

  if (empty($_GET['thok']) || !drupal_valid_token($_GET['thok'], 'flashcard_toggle_hide' . $cid)) {
    return MENU_ACCESS_DENIED;
  }

  $stats = flashcard_load_stats($cid);
  $stats->hide = $stats->hide == 1 ? 0 : 1;
  flashcard_save_stats($stats);

  if ($is_ajax) {
    $commands = array();
    $commands[] = ajax_command_invoke('#flashcard-toogle-hide-link-' . $cid,
      'toggleClass', array('flashcard-hidden', $stats->hide));
    //$commands[] = ajax_command_replace('#flashcard-toggle-hide-link-' . $cid,
      //flashcard_get_toggle_hide_link($cid, $stats->hide) . ' repl');
    return array(
      '#type' => 'ajax',
      '#commands' => $commands,
    );
  }
  else {
    $build['message']['#markup'] = 'Card ' . $cid . ($stats->hide ? ' set to hidden' : ' set to shown');
    return $build;
  }
}

/**
 * Function flashcard_toggle_audioreview().
 */
function flashcard_toggle_audioreview($ajax, $cid) {

  $is_ajax = $ajax === 'ajax';

  if (empty($_GET['taok']) || !drupal_valid_token($_GET['taok'], 'flashcard_toggle_audioreview' . $cid)) {
    return MENU_ACCESS_DENIED;
  }

  $stats = flashcard_load_stats($cid);
  $stats->audioreview = $stats->audioreview == 1 ? 0 : 1 ;
  flashcard_save_stats($stats);

  $stats = flashcard_load_stats($cid);

  if ($is_ajax) {
    $commands = array();
    $commands[] = ajax_command_invoke('#flashcard-toogle-audio-link-' . $cid,
      'toggleClass', array('flashcard-audioreview-enabled', $stats->audioreview));
    //$commands[] = ajax_command_replace('#flashcard-toggle-hide-link-' . $cid,
      //flashcard_get_toggle_hide_link($cid, $stats->hide) . ' repl');
    return array(
      '#type' => 'ajax',
      '#commands' => $commands,
    );
  }
  else {
    $build['message']['#markup'] = 'Card ' . $cid . ($stats->audioreview ? ' set to audioreview' : 'un-set from audioreview');
    return $build;
  }
}

/**
 * Function flashcard_toggle_writereview().
 */
function flashcard_toggle_writereview($ajax, $cid) {

  $is_ajax = $ajax === 'ajax';

  if (empty($_GET['twok']) || !drupal_valid_token($_GET['twok'], 'flashcard_toggle_writereview' . $cid)) {
    return MENU_ACCESS_DENIED;
  }

  $stats = flashcard_load_stats($cid);
  $stats->writereview = $stats->writereview == 1 ? 0 : 1;
  flashcard_save_stats($stats);

  if ($is_ajax) {
    $commands = array();
    $commands[] = ajax_command_invoke('#flashcard-toogle-write-link-' . $cid,
      'toggleClass', array('flashcard-writereview-enabled', $stats->writereview));
    //$commands[] = ajax_command_replace('#flashcard-toggle-hide-link-' . $cid,
      //flashcard_get_toggle_hide_link($cid, $stats->hide) . ' repl');
    return array(
      '#type' => 'ajax',
      '#commands' => $commands,
    );
  }
  else {
    $build['message']['#markup'] = 'Card ' . $cid . ($stats->writereview ? ' set to hidden' : ' set to shown');
    return $build;
  }
}

/**
 * Function flashcard_get_delete_recording_link().
 */
function flashcard_get_delete_recording_link($cid, $value) {
  $query = array(
    'tok' => drupal_get_token('flashcard_delete_recording' . $cid),
  ) + drupal_get_destination();

  $classes = ['use-ajax delete'];
  if (!$value) {
    $classes[] = 'recording-hide';
  }
  return l('&Cross;', 'flashcard/delete/recording/nojs/' . $cid, array(
    'query' => $query, 
    'html' => TRUE,
    'attributes' => array(
      'class' => $classes,
    )
  ));
  
}

/**
 * Function flashcard_delete_recording().
 */
function flashcard_delete_recording($ajax, $cid) {

  $is_ajax = $ajax === 'ajax';

  if (empty($_GET['tok']) || !drupal_valid_token($_GET['tok'], 'flashcard_delete_recording' . $cid)) {
    return MENU_ACCESS_DENIED;
  }

  global $user;

  $outdir = 'public://flashcard/recordings/' . $user->uid; 
  file_prepare_directory($outdir, FILE_CREATE_DIRECTORY);
  $outdir = drupal_realpath($outdir);
  $fname = $outdir . '/' . $cid . '.mp3';
  if (file_exists($fname)) {
    unlink($fname);
  }

  if ($is_ajax) {
    $commands = array();
    $commands[] = ajax_command_invoke('.flashcard-' . $cid . ' .play-rec',
      'toggleClass', array('recording-hide', 0));
    $commands[] = ajax_command_invoke('.flashcard-' . $cid . ' .delete',
      'toggleClass', array('recording-hide', 0));
    //$commands[] = ajax_command_replace('#flashcard-toggle-hide-link-' . $cid,
      //flashcard_get_toggle_hide_link($cid, $stats->hide) . ' repl');
    return array(
      '#type' => 'ajax',
      '#commands' => $commands,
    );
  }
  else {
    $build['message']['#markup'] = 'Recording ' . $cid . ' deleted...';
    return $build;
  }
}

/**
 * Function flashcard_upload_audio().
 */
function flashcard_upload_audio() {
  global $user;
  $outdir = 'public://flashcard/recordings/' . $user->uid; 
  file_prepare_directory($outdir, FILE_CREATE_DIRECTORY);
  $outdir = drupal_realpath($outdir);

  $data = print_r($_FILES, true);

  $success = FALSE;
  if (!empty($_FILES) && isset($_FILES['audiofile'])) {
    $f = (object) $_FILES['audiofile'];
    $outFname = $outdir . '/' . $f->name;
    $success = copy($f->tmp_name, $outFname);
    chmod($outFname, 0777);
    $bn = basename($f->name, '.ogg');
    $pathBn = $outdir . '/' . $bn;
    $mp3 = $pathBn . '.mp3';
    $ogg = $pathBn . '.ogg';
    if (file_exists($mp3)) {
      unlink($mp3);
    }
    $options ="-vn -ar 44100 -ac 2 -ab 192k -f mp3";
    $options ="-vn -ar 22050 -ac 2 -ab 45k -f mp3";
    $cmd = 'ffmpeg -i "' . $ogg . '" ' . $options . ' "' . $mp3 . '"';
    `$cmd`;
    unlink($pathBn . '.ogg');
    chmod($mp3, 0777);
  }

  $out = array(
    'success' => $success ? 1 : 0,
  );
  drupal_json_output($out);
}

/**
 * Function flashcard_get_user_settings().
 */
function flashcard_get_user_settings($key = FALSE) {
  global $user;

  $set_key = 'flashcard_' . $user->uid . '_play';
  $set = variable_get($set_key, array());
  $append = array(
    'training' => array(
      'startat' => 0,
      'autoplay' => FALSE,
      'play_recordings' => 'play_recordings',
      'play_audioreview' => 'play_audioreview',
      'play_writereview' => FALSE,
      'play_unseen_cards' => 'play_unseen_cards',
      'play_hidden_cards' => FALSE,
    ),
    'listing' => array(
      'show_writereview' => 'show_writereview',
      'show_audioreview' => 'show_audioreview',
      'show_hidden' => 'show_hidden',
      'show_unseen' => 'show_unseen',
    ),
  );
  foreach($append as $k=>$v) {
    $set[$k] += $v;
  }
  return $key ? (object) $set[$key] : $set;
}

/**
 * Function flashcard_config_form().
 */
function flashcard_config_form($form, $form_state) {
  $set = flashcard_get_user_settings();

  $form['tc'] = array(
    '#type' => 'fieldset',
    '#title' => t('Trainning'),
    '#tree' => FALSE,
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );

  $form['tc']['training'] = array(
    '#type' => 'checkboxes',
    '#options' => array(
      'autoplay' => t('Autoplay'),
      'play_recordings' => t('Play user recorded files as well.'),
      'play_audioreview' => t('Play cards marked for audioreview'),
      'play_writereview' => t('Play cards marked for write review'),
      'play_unseen_cards' => t('Play unseen cards'),
      'play_hidden_cards' => t('Play hidden cards'),
    ),
    '#default_value' => $set['training'],
  );

  $form['tc']['startat'] = array(
    '#title' => t('Start at card ID'),
    '#type' => 'textfield',
    '#size' => 12,
    '#required' => TRUE,
    '#default_value' => $set['training']['startat'],
    '#autocomplete_path' => FALSE,
  );

  $form['lc'] = array(
    '#type' => 'fieldset',
    '#title' => t('Listing'),
    '#tree' => FALSE,
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );

  $form['lc']['listing'] = array(
    '#type' => 'checkboxes',
    '#options' => array(
      'show_audioreview' => t('Show cards for audioreview'),
      'show_writereview' => t('Show cards for writereview'),
      'show_hidden' => t('Show hidden'),
      'show_unseen' => t('Show unseen'),
    ),
    '#default_value' => $set['listing'],
  );

  $form['actions']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save'),
  );

  $form['links'] = array(
    '#theme' => 'item_list',
    '#items' => flashcard_get_links('config'),
  );
  return $form;
}

/**
 * Function flashcard_config_form_submit().
 */
function flashcard_config_form_submit($form, &$form_state) {
  global $user;
  $set = flashcard_get_user_settings();
  $v = $form_state['values'];

  $set['listing'] = $v['listing'];
  $set['training'] = $v['training'];
  $set['training']['startat'] = $v['startat'];


  $set_key = 'flashcard_' . $user->uid . '_play';
  variable_set($set_key, $set);
  drupal_set_message(t('Saved successfully.'));
}

/**
 * Function flashcard_progress_chart().
 */
function flashcard_progress_chart() {

  global $user;

  $modpath = drupal_get_path('module', 'flashcard');
  drupal_add_css($modpath . '/css/pie.css');

  $stats = new stdClass();
  //count all cards:
  $rez = db_select('flashcard', 't')
    ->fields('t', array('cid'))->execute();
  $stats->total_cards = $rez->rowCount();

  /*

  $query = db_select('flashcard_user_data', 'd')
    ->fields('d', array('cid'))
    ->condition('d.uid', $user->uid);
  $q = $query;
  $rez = $q->condition('d.hide', 1)->execute();
  $stats->hiden_cards = $rez->rowCount();

  $q = $query;
  $or = db_or()->condition('d.audioreview', 1)->condition('d.writereview', 1);
  $rez = $q->condition('d.hide', 0)->condition($or)->execute();
  $stats->ongoing_cards = $rez->rowCount();

  $q = $query;
  $rez = $q->condition('d.hide', 0)->condition('d.audioreview', 1)->execute();
  $stats->to_audioreview = $rez->rowCount();

  $q = $query;
  $rez = $q->condition('d.hide', 0)->condition('d.writereview', 1)->execute();
  $stats->to_writereview = $rez->rowCount();
  */

  $query = db_select('flashcard_user_data', 't');
  $query->addExpression('SUM(t.hide)', 'hiden_cards');
  $query->addExpression('SUM(t.audioreview * (1-t.hide))', 'to_audioreview');
  $query->addExpression('SUM(t.writereview * (1-t.hide))', 'to_writereview');
  $query->addExpression('SUM(t.writereview * t.audioreview * (1-t.hide))', 'common');

  $rez = $query->execute();
  $r = $rez->fetchObject();
  foreach ($r as $k=>$v) {
    $stats->{$k} = $v;
  }
  $percent = new stdClass();
  foreach($stats as $k=>$v) {
    $percent->$k = sprintf("%.1f", $v * 100 / $stats->total_cards);
  }
  $stats->percent = $percent;
  $build = array(
    '#theme' => 'flashcard_progress',
    '#stats' => $stats,
  );

  return $build;
}
